"""
NOSTALGIA Chart Render 主题配置
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Tuple

from PIL import ImageFont


Color = Tuple[int, int, int, int]


def load_font(size: int) -> ImageFont.FreeTypeFont:
    paths = [
        "C:/Windows/Fonts/msyh.ttc",
        "C:/Windows/Fonts/msyhbd.ttc",
        "C:/Windows/Fonts/simhei.ttf",
        "C:/Windows/Fonts/arial.ttf",
        "C:/Windows/Fonts/segoeui.ttf",
    ]
    for p in paths:
        try:
            return ImageFont.truetype(p, size)
        except Exception:
            continue
    return ImageFont.load_default()


@dataclass
class Theme:
    # 尺寸
    track_width: int = 900
    track_reserved_top: int = 80
    track_reserved_bottom: int = 60
    key_count: int = 28
    resize: float = 2.2
    margin_left: int = 120
    margin_right: int = 200
    margin_bg: int = 40
    note_height: int = 24
    note_width_scale: float = 1.3
    note_corner_radius: int = 0
    note_border: int = 2
    judge_line_offset: int = 100
    bar_line_width: int = 2
    beat_line_width: int = 1

    # 颜色
    track_bg: Color = (28, 28, 36, 255)
    track_bg_alt: Color = (32, 32, 42, 255)
    track_split_line: Color = (60, 60, 75, 180)
    judge_line: Color = (255, 255, 255, 200)
    beat_line: Color = (120, 120, 120, 80)
    velocity_zone_light_layer: Color = (120, 205, 255, 42)
    velocity_zone_heavy_layer: Color = (255, 232, 120, 48)
    transparent: Color = (255, 255, 255, 0)

    note_colors: dict[int, Color] = field(default_factory=lambda: {
        0: (100, 180, 255, 230),
        2: (120, 220, 160, 200),
        4: (220, 120, 220, 220),
        8: (255, 100, 100, 220),
        10: (255, 200, 80, 230),
        12: (180, 180, 180, 220),
        64: (255, 220, 60, 220),
    })

    text_title: Color = (240, 240, 240, 255)
    text_subtitle: Color = (180, 180, 180, 255)
    text_stats: Color = (200, 200, 200, 255)
    text_bpm: Color = (100, 200, 255, 255)
    text_bar_beat: Color = (150, 150, 150, 255)

    # 字体
    font_title: ImageFont.FreeTypeFont = field(default_factory=lambda: load_font(36))
    font_artist: ImageFont.FreeTypeFont = field(default_factory=lambda: load_font(24))
    font_stats: ImageFont.FreeTypeFont = field(default_factory=lambda: load_font(20))
    font_bpm: ImageFont.FreeTypeFont = field(default_factory=lambda: load_font(16))
    font_bar_beat: ImageFont.FreeTypeFont = field(default_factory=lambda: load_font(14))
    font_small: ImageFont.FreeTypeFont = field(default_factory=lambda: load_font(12))

    slogan: str = "Generated by NOSTALGIA Chart Render"

    @property
    def key_width(self) -> float:
        return self.track_width / self.key_count


DEFAULT_THEME = Theme()
